# 各サービスを定義
services:
    # webサービスに必要な各コンテナを定義
    web:
        # Dockerfileを使用して新しいイメージをビルドするように指示
        # buildキーは新しいDockerイメージをビルドする場合に使用
        build:
            # Dockerイメージのビルドに使用されるファイルを指定するディレクトリパス
            context: ./nginx-custom
            # Dockerfileの名前を指定
            dockerfile: Dockerfile
        # このサービスのコンテナ名を指定
        container_name: nginx
        # 8080はホストマシンのポート
        # 80はnginxコンテナのポート
        ports:
            - "8080:80"
        # 同期設定
        volumes:
            - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/public
        # phpサービスに依存
        depends_on:
            - php
        # app-networkネットワークに接続
        networks:
            - app-network

    php:
        # Dockerfileを使用して新しいイメージをビルドするように指示
        # buildキーは新しいDockerイメージをビルドする場合に使用
        build:
            # Dockerイメージのビルドに使用されるファイルを指定するディレクトリパス
            context: .
            # Dockerfileの名前を指定
            dockerfile: Dockerfile
        image: portfolio-site-php:latest
        container_name: php
        volumes:
            - ./public:/var/www/public
        networks:
            - app-network

    db:
        # Docker Hubから最新の公式Mysqlイメージを取得
        # imageキーは既存のDockerイメージを使用してコンテナを作成する場合に使用
        image: mysql:5.7
        container_name: mysql
        environment:
            TZ: Asia/Tokyo
            MYSQL_ROOT_PASSWORD: td2S3uI1x@yn6e
            MYSQL_DATABASE: blog
            MYSQL_USER: yaguchi
            MYSQL_PASSWORD: 
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
